### ISSUE TITLE
Error in .subset(x, j) : invalid subscript type 'list'

### ISSUE THREAD

**Issue by chulhongsung** [coatless-rpkg/ucimlrepo#2]
Thank you for sharing good package! 

I find that the error in title occurs when loading some datasets such as 'id = 332' and '891'.

``fetch_ucirepo(id=332)``

Could you fix it for R users?

**Comment by coatless** [comment]
@chulhongsung thanks for the report.

The issue here is two-fold:

1. The `ID` column wasn't being unlisted; and,
2. Some of the variables inside the metadata were padded with spaces causing the subset operation to fail. 

This should be addressed by #5.
